

VV=char('/media/tw260/T7/Effort/fMRI_BIDS/derivatives/fmriprep/sub-s01/func/sub-s01_task-effort_run-1_space-MNI152NLin2009cAsym_desc-preproc_bold.nii',...
    '/media/tw260/T7/Effort/ROIs/MD rois/L_AI.nii',...
    '/media/tw260/T7/Effort/ROIs/MD rois/R_AI.nii',...
    '/media/tw260/T7/Effort/ROIs/MD rois/L_aMFG.nii',...
    '/media/tw260/T7/Effort/ROIs/MD rois/R_aMFG.nii',...
    '/media/tw260/T7/Effort/ROIs/MD rois/L_preSMA.nii',...
    '/media/tw260/T7/Effort/ROIs/MD rois/R_preSMA.nii',...
    '/media/tw260/T7/Effort/ROIs/MD rois/L_FEF.nii',...
    '/media/tw260/T7/Effort/ROIs/MD rois/R_FEF.nii',...
    '/media/tw260/T7/Effort/ROIs/MD rois/L_IPS.nii',...
    '/media/tw260/T7/Effort/ROIs/MD rois/R_IPS.nii',...
    '/media/tw260/T7/Effort/ROIs/MD rois/L_mMFG.nii',...
    '/media/tw260/T7/Effort/ROIs/MD rois/R_mMFG.nii',...
    '/media/tw260/T7/Effort/ROIs/MD rois/L_pMFG.nii',...
    '/media/tw260/T7/Effort/ROIs/MD rois/R_pMFG.nii',...
    '/media/tw260/T7/Effort/ROIs/brainmask.nii');
spm_reslice(VV,struct('mean',false,'which',1,'interp',0)); % 1 for linear


