

VV=char('/media/tw260/X6/Effort/fMRI_BIDS/derivatives/fmriprep/sub-s01/func/sub-s01_task-effort_run-1_space-MNI152NLin2009cAsym_desc-preproc_bold.nii',...
    '/media/tw260/X6/Effort/ROIs/MD rois/bilateral/AI.nii',...
    '/media/tw260/X6/Effort/ROIs/MD rois/bilateral/aMFG.nii',...
    '/media/tw260/X6/Effort/ROIs/MD rois/bilateral/preSMA.nii',...
    '/media/tw260/X6/Effort/ROIs/MD rois/bilateral/FEF.nii',...
    '/media/tw260/X6/Effort/ROIs/MD rois/bilateral/IPS.nii',...
    '/media/tw260/X6/Effort/ROIs/MD rois/bilateral/mMFG.nii',...
    '/media/tw260/X6/Effort/ROIs/MD rois/bilateral/pMFG.nii');
spm_reslice(VV,struct('mean',false,'which',1,'interp',0)); % 1 for linear


